Update build-k2p.yml

diff --git a/.github/workflows/build-k2p.yml b/.github/workflows/build-k2p.yml
--- a/.github/workflows/build-k2p.yml
+++ b/.github/workflows/build-k2p.yml
@@ -212,12 +212,44 @@ jobs:
         sed -i "s/FIRMWARE_BUILDS_REV=.*/FIRMWARE_BUILDS_REV=${{ github.event.inputs.firmwarever }}/g" ./versions.inc
         echo '更新版本号时间'
         #########################################################################################
+    - name: Build Firmware
+      env:
+        TNAME: K2P
+      run: |
+        cd /opt/rt-n56u/trunk
+        if [ ! -f configs/templates/$TNAME.config ] ; then
+        echo "configs/templates/$TNAME.config not found "
+        exit 1
+        fi
+        cp -f configs/templates/$TNAME.config .config
         sudo ./clear_tree
         sudo ./build_firmware_modify $TNAME 0
-        sudo mv -f images/*.trx /opt/images/
-    - name : Upload packages
-      uses: actions/upload-artifact@master
-      if: always()
+        sudo mv -f images/*.trx /opt/images/${TNAME}_Hanwckf_$(date +"%Y%m%d").trx
+    - name: Organize files
+      id: organize
+      run: |
+        echo "::set-output name=status::success"
+    - name: Upload packages - push to artifact file
+      uses: actions/upload-artifact@main
+      if: steps.organize.outputs.status == 'success'
       with:
         name: Padavan-packages
         path: /opt/images
+      #上传到WeTransfer
+    - name: Upload firmware to WeTransfer
+      id: wetransfer
+      if: steps.organize.outputs.status == 'success'
+      run: |
+        curl -fsSL git.io/file-transfer | sh
+        ./transfer wet  -s -p 16 --no-progress /opt/images/*.trx 2>&1 | tee wetransfer.log
+        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
+        echo "::set-output name=status::success"
+      #上传到奶牛快传
+    - name: Upload firmware to cowtransfer
+      id: cowtransfer
+      if: steps.organize.outputs.status == 'success'
+      run: |
+        curl -sL https://git.io/cowtransfer | sh
+        ./cowtransfer-uploader -s -p 16 --hash /opt/images/*.trx 2>&1 | tee cowtransfer.log
+        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
+        echo "::set-output name=status::success"
